version: '3.8'

services:
  mysql-server:
    image: mysql:8
    container_name: cont-mysqlserver-project
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=adminUser
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=bddnodeproject
    ports:
      - "3314:3306"
    networks:
      - net-mysql-server
    volumes:
      - data-mysql-volume:/var/lib/mysql

networks:
  net-mysql-server:

volumes:
  data-mysql-volume:
