export enum DomainExceptionCode {
	DEFAULT_DOMAIN_EXCEPTION = 'DEFAULT_DOMAIN_EXCEPTION',
	COURSE_NAME_REQUIRED = 'COURSE_NAME_REQUIRED',
	COURSE_DESCRIPTION_REQUIRED = 'COURSE_DESCRIPTION_REQUIRED',
	COURSE_DESCRIPTION_LENGTH_INVALID = 'COURSE_DESCRIPTION_LENGTH_INVALID',
	COURSE_DIFFICULTY_REQUIRED = 'COURSE_DIFFICULTY_REQUIRED',
	COURSE_TECHNOLOGY_REQUIRED = 'COURSE_TECHNOLOGY_REQUIRED',
	COURSE_GUID_INVALID = 'USER_GUID_INVALID',
	COURSE_NOT_FOUND = 'COURSE_NOT_FOUND',
}

export abstract class DomainException extends Error {
	constructor(message?: string) {
		super(message)
		this.name = DomainExceptionCode.DEFAULT_DOMAIN_EXCEPTION
	}
}
